version: '3.8'
    services:
      mediamtx:
        image: bluenviron/mediamtx
        ports:
          - "8888:8888" # HLS
          - "1935:1935" # RTMP
          - "9997:9997" # Control Panel
        volumes:
          - ./mediamtx.yml:/mediamtx.yml
        restart: unless-stopped
