version: '3.8'
services:
    mediamtx:
        build:
            context: .
            dockerfile: Dockerfile
        environment:
            - SERVICE_FQDN_MEDIAMTX
        labels:
            - caddy_0.encode=zstd gzip
            - caddy_0.handle_path.0_reverse_proxy={{upstreams 8888}}
            - caddy_0.handle_path=/*
            - caddy_0.header=-Server
        restart: unless-stopped
