version: '3.8'
services:
    mediamtx:
        build:
            context: .
            dockerfile: Dockerfile
        environment:
            - SERVICE_FQDN_MEDIAMTX
        ports:
            - '172.22.22.108:1935:1935'
            - '8888'
        labels:
            - caddy_0.encode=zstd gzip
            - caddy_0=${SERVICE_FQDN_MEDIAMTX}
            - caddy_0.reverse_proxy={{upstreams 8888}}
            - caddy_0.handle_path=/*
            - caddy_0.header=-Server
        restart: unless-stopped
