version: '3.8'
services:
    mediamtx:
        build:
            context: .
            dockerfile: Dockerfile
        environment:
            - SERVICE_FQDN_MEDIAMTX
        ports:
            - '8888' # HLS
            - '12440:1935' # RTMP
            - '12441:9997' # Control Panel
        labels:
            - caddy_0.encode=zstd gzip
            - caddy_0.handle_path.0_reverse_proxy={{upstreams 8888}}
            - caddy_0.handle_path=/*
            - caddy_0.header=-Server
            - caddy_ingress_network=coolify
        restart: unless-stopped
